#!/bin/sh

BUILD_TIME=`date '+%Y-%m-%d %H:%M:%S'`

if [ $? -ne 0 ]; then
	BUILD_TIME="UNKNOWN BUILD TIME"
fi

cat << ENDOFFILE

/* Do NOT edit this file! His content is created automatically. */

char* build_time_get ( void ) { return "${BUILD_TIME}"; }

/* end of src/build_time.c */

ENDOFFILE

exit $?
