#!/bin/sh

BUILD_TIME=`/bin/date '+%Y-%m-%d %H:%M:%S'`

/bin/cat << ENDOFFILE

/* Do NOT edit this file! His content is created automatically. */

char* build_time_get ( void ) { return "${BUILD_TIME}"; }

/* end of src/build_time.c */

ENDOFFILE

exit $?
