#!/bin/sh

BUILD_TIME=`date '+%Y-%m-%d %H:%M:%S'`

if [ $? -ne 0 ]; then
	BUILD_TIME="UNKNOWN BUILD TIME"
fi

REVISION_TXT=`svn info|egrep "^Revision:"`

REVISION_INT=`echo ${REVISION_TXT}|sed -e s/^Revision://`

cat << ENDOFFILE

/* Do NOT edit this file! His content is created automatically. */

char* build_time_get ( void ) { return "${BUILD_TIME}"; }

char* build_time_get_revision_txt ( void ) { return "${REVISION_TXT}"; }

int build_time_get_revision_int ( void ) { return ${REVISION_INT}; }

/* end of src/build_time.c */

ENDOFFILE

exit $?
